// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GO0CiBY5cc9SSzNoIfgNfqRrIYfYxhc',
    appId: '1:495876470631:web:3fa18f1854281495a621c2',
    messagingSenderId: '495876470631',
    projectId: 'yahtzee-44b21',
    authDomain: 'yahtzee-44b21.firebaseapp.com',
    storageBucket: 'yahtzee-44b21.firebasestorage.app',
    measurementId: 'G-3ZVXEQ75FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoqCz7PTz8G1GWfSciFA5Dz0MPJITu_hQ',
    appId: '1:495876470631:android:bdfb8f054b2f6d09a621c2',
    messagingSenderId: '495876470631',
    projectId: 'yahtzee-44b21',
    storageBucket: 'yahtzee-44b21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCha8sy_VevzPm856YbeI0WpikyER7c0',
    appId: '1:495876470631:ios:2eeddc502c7787dfa621c2',
    messagingSenderId: '495876470631',
    projectId: 'yahtzee-44b21',
    storageBucket: 'yahtzee-44b21.firebasestorage.app',
    iosBundleId: 'com.example.yahtzee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqCha8sy_VevzPm856YbeI0WpikyER7c0',
    appId: '1:495876470631:ios:2eeddc502c7787dfa621c2',
    messagingSenderId: '495876470631',
    projectId: 'yahtzee-44b21',
    storageBucket: 'yahtzee-44b21.firebasestorage.app',
    iosBundleId: 'com.example.yahtzee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2GO0CiBY5cc9SSzNoIfgNfqRrIYfYxhc',
    appId: '1:495876470631:web:7750196e3e3105fea621c2',
    messagingSenderId: '495876470631',
    projectId: 'yahtzee-44b21',
    authDomain: 'yahtzee-44b21.firebaseapp.com',
    storageBucket: 'yahtzee-44b21.firebasestorage.app',
    measurementId: 'G-MXF8L8MR5V',
  );
}
